packageExtensions:
  "@types/node@*":
    dependencies:
      "@types/events": "*"
  "@types/amqplib@*":
    dependencies:
      "bluebird": "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
pnpMode: loose
yarnPath: .yarn/releases/yarn-berry.js
