packageExtensions:
  "@types/amqplib@*":
    dependencies:
      bluebird: "*"
  "@types/node@*":
    dependencies:
      "@types/events": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.js
