version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sender:
    image: sender:v1
    build:
      context: .
      dockerfile: .docker/sender/Dockerfile
    depends_on:
      - rabbitmq